from setuptools import setup, find_packages

setup(
    name='mcqgen',
    version='0.1.0',
    author='Your Name',
    author_email='your.email@example.com',
    description='A generative AI project for MCQ generation',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/generative-ai-project',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3.8',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.8,<3.9',
    install_requires=[
        'numpy>=1.19.0,<1.25.0',
        'pandas>=1.1.0,<2.0.0',
        'matplotlib>=3.3.0,<4.0.0',
        'tensorflow>=2.4.0,<2.11.0',
        'torch>=1.9.0,<2.0.0',
        'transformers>=4.5.0,<5.0.0',
        'nltk>=3.5',
        'spacy>=3.0.0,<4.0.0',
        'Pillow>=8.0.0,<10.0.0',
        'opencv-python>=4.5.0,<5.0.0',
        'scikit-learn>=0.24.0,<1.2.0',
        'scipy>=1.5.0,<1.10.0',
        'tqdm>=4.50.0',
        'requests>=2.25.0',
        'python-dotenv>=0.19.0',
    ],
    extras_require={
        'dev': [
            'pytest>=6.0',
            'pytest-cov>=2.10',
            'black>=21.0',
            'flake8>=3.8',
            'mypy>=0.900',
        ],
        'jupyter': [
            'jupyter>=1.0.0',
            'ipykernel>=6.0.0',
        ],
    },
)
